# Uncomment this line to define a global platform for your project
# platform :ios, '8.1'

target 'VimeoTest' do
pod "AFNetworking", "~> 2.0"
pod 'SDWebImage', '~>3.6'
pod 'DLAlertView'
end

target 'VimeoTestTests' do

end

